### ISSUE TITLE
Cannot work on worktree

### ISSUE THREAD

**Issue by codable** [junkblocker/patchreview-vim#13]
It doesn't work inside of an worktree.
> Error detected while processing function patchreview#diff_review[55]..patchreview#get_patchfile_lines:
line    6:
E605: Exception not caught: File  is not readable

**Comment by junkblocker** [comment]
A little more information would be useful. What command did you run? Was it in a top level directory in a version controlled worktree? And if it was in a git or other repo, please tell the name of that version control system.

**Comment by codable** [comment]
```sh
git worktree add ../another-worktree master
cd ../another-worktree
```
in this worktree, change something, then do according to the README.md
```vim
:DiffReview git diff master --no-color -U5
```

**Comment by junkblocker** [comment]
Ah, worktrees are not something I had played with. Will add support as time permits. patches are welcome if somebody wants to take a shot at it before I do.
