### ISSUE TITLE
459b7ed breaks syntax highlighting

### ISSUE THREAD

**Issue by heeen** [junkblocker/patchreview-vim#15]
I have a syntax plugin that hooks itself with autocmd and after that changeset it does not get enabled anymore

**Comment by junkblocker** [comment]
The goal of all the ``noautocmd`` I added in there was to keep the plugin operation independent of anything that might break functioning, a problem I had observed sometimes. I'll think about it and see if it should be reverted.

**Comment by junkblocker** [comment]
Fixed in b57bceac
