### ISSUE TITLE
First tab does not show diff

### ISSUE THREAD

**Issue by heeen** [junkblocker/patchreview-vim#16]
The first tab shows the same file as the second tab, but without a diff split.

It would be nice if the first tab could show the commit message, then the files in subsequent tabs.

**Comment by junkblocker** [comment]
patchreview tries to leave the current buffer untouched and only opens diffs in new tabs to avoid any sort of workflow conflicts. Due to that and also it having multiple modes unrelated to version control, showing a commit message is not going to make sense.
