### ISSUE TITLE
error on running :DIffReview

### ISSUE THREAD

**Issue by dyfrgi** [junkblocker/patchreview-vim#7]
Error detected while processing function patchreview#diff_review..39:
line    2:
E721: Duplicate key in Dictionary: "diff"
E15: Invalid expression: {'diff': 0, 'diff': l:diff}  

subversion.vim line 15 does indeed have that dictionary on it. I'm not clear on how that's supposed to work. Maybe it worked in some older version of vim?

**Comment by junkblocker** [comment]
Fixed by junkblocker/patchreview-vim@9d0b64420a0d3cbc19e0b6e7a3057b14d9708da9
